-- Entrega 1 / API v2 Snap-first schema (synchronous phase).
-- The schema is already tenant-aware (`assinatura_id`) even though phase 1 uses only the seeded
-- `default` assinatura. This avoids a breaking migration when auth/tenant context is introduced.

-- Assinatura (tenant) registry. In Entrega 1 it stores the seeded `default` tenant.
create table assinatura (
    id bigint generated by default as identity primary key,
    codigo varchar(100) not null,
    nome varchar(200) not null,
    api_token varchar(200),
    status varchar(40) not null,
    created_at timestamp with time zone not null
);

create unique index uk_assinatura_codigo on assinatura(codigo);
create unique index uk_assinatura_api_token on assinatura(api_token);

-- Subject templates are scoped by assinatura. Entrega 1 uses one seeded default template.
create table subject_template (
    id bigint generated by default as identity primary key,
    assinatura_id bigint not null,
    nome varchar(200) not null,
    slug varchar(120) not null,
    ativo boolean not null,
    schema_json clob,
    is_default boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_subject_template_assinatura foreign key (assinatura_id) references assinatura(id)
);

create unique index uk_subject_template_ass_slug on subject_template(assinatura_id, slug);
create index idx_subject_template_ass_ativo on subject_template(assinatura_id, ativo);

-- Minimal user registry. Users are resolved from request payload (`email` + `nickname`) for now.
create table usuario (
    id bigint generated by default as identity primary key,
    nickname varchar(120) not null,
    email varchar(320) not null,
    status varchar(40) not null,
    created_at timestamp with time zone not null
);

create unique index uk_usuario_email on usuario(email);
create index idx_usuario_nickname on usuario(nickname);

-- Video catalog reused across snaps. `url_hash` enables deduplication by canonical URL.
create table video (
    id uuid primary key,
    assinatura_id bigint not null,
    original_url clob not null,
    canonical_url clob,
    url_hash varchar(64) not null,
    video_probe_json clob,
    created_by_usuario_id bigint,
    created_at timestamp with time zone not null,
    constraint fk_video_assinatura foreign key (assinatura_id) references assinatura(id),
    constraint fk_video_usuario foreign key (created_by_usuario_id) references usuario(id)
);

create unique index uk_video_ass_urlhash on video(assinatura_id, url_hash);
create index idx_video_ass_created on video(assinatura_id, created_at desc);

-- Main Snap record storing request snapshot + processing outputs (JSON blobs + summary fields).
create table snap (
    id uuid primary key,
    assinatura_id bigint not null,
    video_id uuid not null,
    created_by_usuario_id bigint not null,
    subject_template_id bigint,
    nickname_snapshot varchar(120) not null,
    email_snapshot varchar(320) not null,
    tipo_snap varchar(20) not null,
    status varchar(40) not null,
    public_share_token varchar(200),
    is_public boolean not null,
    data_filmagem timestamp with time zone not null,
    video_url clob not null,
    start_seconds double precision,
    start_frame bigint,
    resolved_start_seconds double precision,
    duration_seconds double precision not null,
    snapshot_duration_seconds double precision not null,
    fps integer not null,
    max_width integer not null,
    format varchar(10) not null,
    quality integer,
    subject_id varchar(200) not null,
    subject_json clob not null,
    overlay_json clob,
    video_probe_json clob,
    snapshot_video_json clob,
    frames_json clob,
    frame_count integer not null,
    output_dir clob,
    error_message clob,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    processed_at timestamp with time zone,
    constraint fk_snap_assinatura foreign key (assinatura_id) references assinatura(id),
    constraint fk_snap_video foreign key (video_id) references video(id),
    constraint fk_snap_usuario foreign key (created_by_usuario_id) references usuario(id),
    constraint fk_snap_template foreign key (subject_template_id) references subject_template(id)
);

create unique index uk_snap_public_share_token on snap(public_share_token);
create index idx_snap_ass_video_created on snap(assinatura_id, video_id, created_at asc);
create index idx_snap_ass_subject_created on snap(assinatura_id, subject_id, created_at desc);
create index idx_snap_ass_user_created on snap(assinatura_id, created_by_usuario_id, created_at desc);

-- Flattened subject attributes to support indexed searches without parsing JSON on every request.
create table snap_subject_attr (
    id bigint generated by default as identity primary key,
    snap_id uuid not null,
    assinatura_id bigint not null,
    video_id uuid not null,
    subject_id varchar(200) not null,
    attr_key varchar(120) not null,
    value_type varchar(20) not null,
    string_value varchar(1000),
    number_value numeric(20, 6),
    created_at timestamp with time zone not null,
    constraint fk_snap_subject_attr_snap foreign key (snap_id) references snap(id),
    constraint fk_snap_subject_attr_ass foreign key (assinatura_id) references assinatura(id)
);

create index idx_snap_attr_string on snap_subject_attr(assinatura_id, attr_key, string_value);
create index idx_snap_attr_number on snap_subject_attr(assinatura_id, attr_key, number_value);
create index idx_snap_attr_subject_string on snap_subject_attr(assinatura_id, subject_id, attr_key, string_value);
create index idx_snap_attr_subject_number on snap_subject_attr(assinatura_id, subject_id, attr_key, number_value);
