-- Entrega 4 (slice 1): database-backed queue for asynchronous snap processing.
--
-- This table decouples `POST /v2/snaps` request acceptance from FFmpeg execution while keeping
-- the public `snap` contract stable. The `snap` row remains the source of truth for request/result
-- data; this job table tracks scheduling/claiming/retry lifecycle.

create table snap_processing_job (
    id bigint generated by default as identity primary key,
    snap_id uuid not null,
    assinatura_id bigint not null,
    status varchar(40) not null,
    attempts integer not null,
    max_attempts integer not null,
    next_run_at timestamp with time zone not null,
    locked_at timestamp with time zone,
    lock_owner varchar(200),
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    last_error text,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_snap_processing_job_snap foreign key (snap_id) references snap(id),
    constraint fk_snap_processing_job_assinatura foreign key (assinatura_id) references assinatura(id)
);

-- One processing job per snap in the current model. Future evolutions can split jobs if needed.
create unique index uk_snap_processing_job_snap on snap_processing_job(snap_id);

-- Main worker polling index: only claimable jobs (`PENDING`/`RETRY_WAIT`) whose `next_run_at`
-- is in the past are scanned frequently.
create index idx_snap_processing_job_claim on snap_processing_job(status, next_run_at, created_at);

-- Tenant-scoped introspection/debug support (useful in internal tools/log correlation).
create index idx_snap_processing_job_ass_status on snap_processing_job(assinatura_id, status, created_at desc);

